language: node_js
sudo: required

node_js:
  - "10"

before_install:
  - npm install -g npm@latest
  - npm install -g coveralls
  - npm install -g ganache-cli
  - npm install -g truffle

install:
  - npm install

script:
  - truffle compile
  - ganache-cli -p 8545 > /dev/null &
  - truffle migrate
  - npm run coverage && cat coverage/lcov.info | coveralls
